name: Publish Playground
on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: Src/CSharpier.Playground

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      -
        uses: actions/checkout@v2
      -
        run: dotnet test ../CSharpier.Tests/CSharpier.Tests.csproj
  publish-playground:
    runs-on: ubuntu-latest
    name: publish playground
    needs: test
    steps:
      - 
        uses: actions/checkout@v2
      - 
        run: dotnet publish -c release --output ../../publish
      -
        run: mkdir offline && touch offline/app_offline.htm
      - 
        name: Upload app_offline.htm
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp://${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "Src/CSharpier.Playground/offline"
          remoteDir: "/csharpier_bntstudios_com"
      -
        name: FTP Deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "publish"
          dist_target_dir: "/csharpier_bntstudios_com"
          delete: "true"
          exclude: "'App_Data' 'app_offline.htm'"
          other_flags: "-p --dereference"
      - 
        name: Delete app_offline.htm
        uses: StephanThierry/ftp-delete-action@releases/v1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: "app_offline.htm"
          workingDir: "/csharpier_bntstudios_com"