name: Publish Nuget
on:
  push:
    branches: [ build-fix ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
      - run: >
          dotnet test Src/CSharpier.Tests/CSharpier.Tests.csproj
          --configuration Release
          --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
          --
          RunConfiguration.CollectSourceInformation=true

  publish-nuget:
    runs-on: ubuntu-latest
    name: publish nuget
    needs: test
    env:
      VERSION_FILE_PATH: Nuget/Build.props
      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
      - name: Publish CSharpier.Core library on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: Src/CSharpier/CSharpier.csproj
          TAG_FORMAT: "*"
      - name: Publish CSharpie dotnet tool on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: Src/CSharpier.Cli/CSharpier.Cli.csproj
          TAG_FORMAT: "*"
      - name: Publish CSharpier.MsBuild library on version change
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: Src/CSharpier.MsBuild/CSharpier.MsBuild.csproj
          TAG_FORMAT: "*"
